name: Build SoundFlowFFmpeg v1

on:
  workflow_dispatch:

# Cancel in-progress runs on new commits to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Windows builds
  build-windows:
    strategy:
      matrix:
        include:
          - arch: x64
            msystem: MINGW64
            mingw-package-prefix: mingw-w64-x86_64
          - arch: x86
            msystem: MINGW32
            mingw-package-prefix: mingw-w64-i686
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.mingw-package-prefix }}-gcc
            ${{ matrix.mingw-package-prefix }}-cmake
            ${{ matrix.mingw-package-prefix }}-ninja
            ${{ matrix.mingw-package-prefix }}-make
            ${{ matrix.mingw-package-prefix }}-pkg-config
            base-devel
            git
            nasm
            yasm

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }}
          cmake --build . --parallel $(nproc) --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soundflow-ffmpeg-win-${{ matrix.arch }}
          path: build/runtimes/win-${{ matrix.arch }}/native/*

  # Linux builds
  build-linux:
    strategy:
      matrix:
        include:
          - arch: x64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install native dependencies
        if: matrix.arch == 'x64'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake nasm yasm pkg-config

      - name: Setup ARM64 cross-compilation
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            build-essential cmake nasm yasm pkg-config

      - name: Configure and Build (x64)
        if: matrix.arch == 'x64'
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_PROCESSOR=x86_64
          cmake --build . --parallel $(nproc) --verbose

      - name: Configure and Build (ARM64)
        if: matrix.arch == 'arm64'
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
          cmake --build . --parallel $(nproc) --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soundflow-ffmpeg-linux-${{ matrix.arch }}
          path: build/runtimes/linux-${{ matrix.arch }}/native/*

  # macOS builds
  build-macos:
    strategy:
      matrix:
        include:
          - arch: x64
            os: macos-13  # Intel
          - arch: arm64
            os: macos-14  # Apple Silicon
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Check if cmake is installed via homebrew and update if needed
          if brew list cmake &>/dev/null; then
            brew upgrade cmake || true
          else
            brew install cmake
          fi
          brew install nasm yasm pkg-config

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.arch }}" = "x64" ]; then
            cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_OSX_ARCHITECTURES=x86_64 \
              -DCMAKE_SYSTEM_PROCESSOR=x86_64
          else
            cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_OSX_ARCHITECTURES=arm64 \
              -DCMAKE_SYSTEM_PROCESSOR=arm64
          fi
          cmake --build . --parallel $(sysctl -n hw.ncpu) --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soundflow-ffmpeg-osx-${{ matrix.arch }}
          path: build/runtimes/osx-${{ matrix.arch }}/native/*

  # Android builds
  build-android:
    strategy:
      matrix:
        include:
          - rid_arch: x64
            abi: x86_64
          - rid_arch: arm
            abi: armeabi-v7a
          - rid_arch: arm64
            abi: arm64-v8a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake nasm yasm pkg-config

      - name: Configure and Build
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=21
          cmake --build . --parallel $(nproc) --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soundflow-ffmpeg-android-${{ matrix.rid_arch }}
          path: build/runtimes/android-${{ matrix.rid_arch }}/native/*

  # FreeBSD build
  build-freebsd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v4

      - name: Build in FreeBSD VM
        uses: cross-platform-actions/action@v0.26.0
        with:
          operating_system: freebsd
          version: '14.0'
          architecture: x86_64
          run: |
            # Install dependencies
            sudo pkg install -y cmake gmake nasm yasm pkgconf bash

            # Create and enter build directory
            mkdir build
            cd build

            # Configure and build
            cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_MAKE_PROGRAM=gmake
            cmake --build . --parallel $(sysctl -n hw.ncpu) --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soundflow-ffmpeg-freebsd-${{ matrix.arch }}
          path: build/runtimes/freebsd-${{ matrix.arch }}/native/*

  # iOS build
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Check if cmake is installed via homebrew and update if needed
          if brew list cmake &>/dev/null; then
            brew upgrade cmake || true
          else
            brew install cmake
          fi
          brew install nasm yasm pkg-config

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
          cmake --build . --parallel $(sysctl -n hw.ncpu) --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: soundflow-ffmpeg-ios-arm64
          path: build/runtimes/ios-arm64/native/*